-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 09, 2019 at 04:42 AM
-- Server version: 10.4.6-MariaDB
-- PHP Version: 7.1.32

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bom`
--

-- --------------------------------------------------------

--
-- Table structure for table `sbom`
--

CREATE TABLE `sbom` (
  `row_id` int(6) NOT NULL,
  `app_id` varchar(15) NOT NULL,
  `app_name` varchar(100) NOT NULL,
  `app_version` varchar(15) NOT NULL,
  `cmp_id` varchar(15) NOT NULL,
  `cmp_name` varchar(100) NOT NULL,
  `cmp_version` varchar(15) NOT NULL,
  `cmp_type` varchar(15) NOT NULL,
  `app_status` varchar(15) NOT NULL,
  `cmp_status` varchar(15) NOT NULL,
  `request_id` varchar(15) NOT NULL COMMENT 'PQR_839_R1, XYZ_789_R2',
  `request_date` date NOT NULL,
  `request_status` varchar(15) NOT NULL COMMENT 'Approved, Pending, Submitted',
  `request_step` varchar(30) NOT NULL COMMENT 'Review Step, Inspection Step, Approval Step',
  `notes` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `sbom`
--

INSERT INTO `sbom` (`row_id`, `app_id`, `app_name`, `app_version`, `cmp_id`, `cmp_name`, `cmp_version`, `cmp_type`, `app_status`, `cmp_status`, `request_id`, `request_date`, `request_status`, `request_step`, `notes`) VALUES
(1, 'BOM-100', 'QuizMaster', '1.1', '101.1', 'DB_Layer', '2.3', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(2, 'BOM-100', 'QuizMaster', '1.1', '101.2', 'Jquery', '4.3', 'open source', 'released', 'approved', '', '0000-00-00', '', '', 'open source, no commercial support'),
(3, 'BOM-100', 'QuizMaster', '1.1', '101.3', 'Bootstrap', '8.5.c', 'open source', 'released', 'pending', '', '0000-00-00', '', '', ''),
(4, 'BOM-100', 'QuizMaster', '1.1', '101.4', 'IconFinder', '2019', 'commercial', 'released', 'submitted', '', '0000-00-00', '', '', ''),
(5, 'BOM-100', 'QuizMaster', '1.1', '101.5', 'Excel', '2019', 'commercial', 'released', 'in_review', '', '0000-00-00', '', '', ''),
(6, '101.1', 'DB_Layer', '2.3', '101.1.1', 'DB_Layer_MySQL', 'v1.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(8, '101.1', 'DB_Layer', '2.3', '101.1.2', 'DB_Layer_DB2', 'v1.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(10, '101.1', 'DB_Layer', '2.3', '101.1.4', 'DB_Layer_Ingress', 'v1.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(11, 'BOM-104', 'QuizMaster', '2.2', '202.2', 'DB_Layer', '2.3', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(12, 'BOM-104', 'QuizMaster', '2.2', '202.2', 'Jquery', '4.3', 'open source', 'released', 'approved', '', '0000-00-00', '', '', 'open source, no commercial support'),
(13, 'BOM-104', 'QuizMaster', '2.2', '202.3', 'Bootstrap', '8.5.c', 'open source', 'released', 'pending', '', '0000-00-00', '', '', ''),
(14, 'BOM-104', 'QuizMaster', '2.2', '202.4', 'IconFinder', '2029', 'commercial', 'released', 'submitted', '', '0000-00-00', '', '', ''),
(15, 'BOM-104', 'QuizMaster', '2.2', '202.5', 'Excel', '2029', 'commercial', 'released', 'in_review', '', '0000-00-00', '', '', ''),
(16, '202.2', 'DB_Layer', '2.3', '202.2.2', 'DB_Layer_Maria', 'v2.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(17, '202.2', 'DB_Layer', '2.3', '202.2.2', 'DB_Layer_DB2', 'v2.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(18, '202.2', 'DB_Layer', '2.3', '202.2.3', 'DB_Layer_Oracle', 'v2.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(19, '202.2', 'DB_Layer', '2.3', '202.2.4', 'DB_Layer_Ingress', 'v2.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', ''),
(20, '202.2', 'DB_Layer', '2.3', '202.2.5', 'DB_Layer_MS_SQL', 'v2.0', 'internal', 'released', 'released', '', '0000-00-00', '', '', '');

INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.1','Apache','5','open source','released','released','GGQ_410_R48','2016-06-28','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.10','Trullium','6','commercial','released','released','LZV_627_R26','2016-07-01','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.11','Bootstrap','2','open source','released','released','HZX_979_R17','2016-07-02','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.12','jQuery','3','open source','released','released','ZPD_992_R30','2016-07-03','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.13','(a) Color Picker','1.1','internal','released','released','NND_946_R15','2016-07-06','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.2','Contact Import','8.9','commercial','released','released','KKP_985_R50','2016-07-06','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.3','Ajax','9','open source','released','released','DQW_484_R47','2016-07-07','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.4','Google Maps','v1.0','API','released','released','EBP_849_R1','2016-07-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.5','mySQL','3','open source','released','released','HOM_656_R41','2016-07-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.6','(a) Picture Place','8.1','internal','released','released','ORS_333_R40','2016-07-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.7','White Pages','2016','commercial','released','released','SQF_953_R29','2016-07-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.8','Acrobat Reader','6','commercial','released','released','KJU_211_R1','2016-07-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-7','(a) Address Book','7','7.7.9','GPS Find Me','9','commercial','released','released','DJT_214_R28','2016-07-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.1','Apache','6','open source','released','released','YNX_606_R25','2016-07-13','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.10','Trullium','6','commercial','released','released','UZR_430_R43','2016-07-14','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.11','Bootstrap','2','open source','released','released','BED_140_R17','2016-07-14','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.12','jQuery','3','open source','released','released','MTU_663_R6','2016-07-15','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.13','(a) Color Picker','1.2','internal','released','released','DMU_856_R26','2016-07-16','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.2','Contact Import','9','commercial','released','released','VGU_960_R31','2016-07-18','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.3','Ajax','10','open source','released','released','KOM_465_R11','2016-07-18','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.4','Google Maps','v1.1','API','released','released','SOH_402_R4','2016-07-19','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.5','mySQL','4','open source','released','released','BQX_355_R43','2016-07-19','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.6','(a) Picture Place','8.1','internal','released','released','HCN_836_R20','2016-07-20','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.7','White Pages','2016','commercial','released','released','IQF_754_R20','2016-07-23','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.8','Acrobat Reader','6','commercial','released','released','ZPY_892_R30','2016-07-24','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-71','(a) Address Book','71','71.71.9','GPS Find Me','10','commercial','released','released','UBX_295_R39','2016-07-25','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.1','Apache','7','open source','released','released','QTK_889_R47','2016-10-24','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.10','(a) Picture Place','8.12','internal','released','released','HRL_945_R50','2016-11-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.11','White Pages','2016','commercial','released','released','TGU_863_R30','2016-11-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.12','Acrobat Reader','6','commercial','released','released','VDC_679_R7','2016-11-14','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.13','GPS Find Me','11','commercial','released','released','GMS_674_R20','2016-11-15','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.2','Trullium','6','commercial','released','released','LAX_993_R12','2016-11-16','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.3','Bootstrap','2','open source','released','released','AFB_180_R1','2016-11-17','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.4','jQuery','3','open source','released','released','ATQ_348_R43','2016-11-17','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.5','(a) Color Picker','1.3','internal','released','released','GUO_611_R26','2016-11-18','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.6','Contact Import','10.1','commercial','released','released','EQB_970_R22','2016-10-28','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.7','Ajax','11','open source','released','released','PPT_866_R12','2016-11-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.8','Google Maps','v1.2','API','released','released','RYR_145_R7','2016-11-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-72','(a) Address Book','72','72.72.9','mySQL','5','open source','released','released','SHU_595_R8','2016-11-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.1','Apache','8','open source','released','released','KEY_461_R17','2016-11-18','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.10','(a) Picture Place','8.13','internal','released','released','VMS_338_R32','2016-11-24','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.11','White Pages','2016','commercial','released','released','LKS_892_R2','2016-11-25','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.12','Acrobat Reader','7','commercial','released','released','GUI_181_R5','2016-11-26','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.13','GPS Find Me','12','commercial','released','released','HQI_641_R28','2016-11-26','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.2','Trullium','6','commercial','released','released','JKJ_740_R19','2016-11-26','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.3','Bootstrap','3','open source','released','released','ZIN_484_R20','2016-11-26','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.4','jQuery','3','open source','released','released','YSL_114_R13','2016-12-01','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.5','(a) Color Picker','1.4','internal','released','released','CCI_429_R6','2016-12-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.6','Contact Import','11','commercial','released','released','OUN_407_R7','2016-11-20','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.7','Ajax','12','open source','released','released','WCE_774_R9','2016-11-20','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.8','Google Maps','v1.3','API','released','released','BRH_602_R11','2016-11-21','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-73','(a) Address Book','73','73.73.9','mySQL','6','open source','released','released','LLX_806_R35','2016-11-21','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.1','Apache','9','open source','released','released','VFT_396_R38','2017-09-03','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.10','(a) Picture Place','8.13','internal','released','released','AQO_671_R47','2017-09-14','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.11','White Pages','2017','commercial','released','released','LHU_687_R48','2017-09-15','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.12','Acrobat Reader','7','commercial','released','released','FWY_333_R12','2017-09-20','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.13','GPS Find Me','13','commercial','released','released','SDI_633_R1','2017-09-20','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.2','Trullium','7','commercial','released','released','HDX_124_R49','2017-09-22','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.3','Bootstrap','3','open source','released','released','KLO_202_R27','2017-09-22','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.4','jQuery','3.1','open source','released','released','QCB_915_R48','2017-09-22','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.5','(a) Color Picker','1.5','internal','released','released','RJO_246_R15','2017-09-22','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.6','Contact Import','12.9','commercial','released','released','AJG_987_R45','2017-09-04','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.7','Ajax','13','open source','released','released','YSK_110_R18','2017-09-05','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.8','Google Maps','v2.0','API','released','released','UFQ_182_R49','2017-09-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-74','(a) Address Book','74','74.74.9','mySQL','7','open source','released','released','OXS_977_R19','2017-09-12','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.1','Apache','10','open source','released','released','JFP_842_R13','2017-09-23','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.10','(a) Picture Place','8.14','internal','released','released','PLY_619_R28','2017-10-01','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.11','White Pages','2017','commercial','released','released','TJF_363_R19','2017-10-05','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.12','Acrobat Reader','7','commercial','released','released','RBI_327_R6','2017-10-07','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.13','GPS Find Me','14','commercial','released','released','LPP_640_R30','2017-10-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.2','Trullium','7','commercial','released','released','TSN_749_R17','2017-10-13','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.3','Bootstrap','3','open source','released','released','BAM_343_R28','2017-10-16','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.4','jQuery','3.1','open source','released','released','VYK_744_R49','2017-10-17','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.5','(a) Color Picker','1.6','internal','released','released','YEV_302_R29','2017-10-17','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.6','Contact Import','13.1','commercial','released','released','QAE_672_R22','2017-09-23','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.7','Ajax','14','open source','released','released','AUL_815_R49','2017-09-25','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.8','Google Maps','v2.1','API','released','released','FBU_386_R24','2017-09-25','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-75','(a) Address Book','75','75.75.9','mySQL','8','open source','released','released','PEE_788_R43','2017-10-01','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.1','Apache','11','open source','review','In_Review','LMC_159_R39','2018-07-06','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.10','(a) Picture Place','8.15','internal','review','Submitted','MOD_666_R24','2018-07-13','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.11','White Pages','2018','commercial','review','Approved','HJE_673_R5','2018-07-14','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.12','Acrobat Reader','8','commercial','review','Pending','QGF_344_R23','2018-07-14','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.13','GPS Find Me','15','commercial','review','Pending','KXJ_841_R26','2018-07-15','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.2','Trullium','8','commercial','review','Approved','CZL_893_R7','2018-07-16','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.3','Bootstrap','3.4','open source','review','Submitted','ZSG_282_R26','2018-07-16','Inspection Step','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.4','jQuery','3.1.1','open source','review','submitted','GXP_709_R10','2018-07-18','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.5','(a) Color Picker','1.7','internal','review','Pending','UWA_885_R25','2018-07-18','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.6','Contact Import','13.4','commercial','review','Pending','BPD_252_R26','2018-07-07','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.7','Ajax','15','open source','review','Approved','MCY_478_R5','2018-07-07','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.8','Google Maps','v2.2','API','review','Approved','GCI_534_R18','2018-07-09','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-76','(a) Address Book','76','76.76.9','mySQL','9','open source','review','Pending','ZMY_735_R5','2018-07-10','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.1','Apache','12','open source','estimation','Submitted','FZO_947_R43','2018-07-19','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.10','(a) Picture Place','8.16','internal','estimation','Pending','RNR_643_R24','2018-07-24','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.11','White Pages','2018','commercial','estimation','Approved','GWY_622_R50','2018-07-26','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.12','Acrobat Reader','8','commercial','estimation','Pending','LXG_657_R43','2018-07-27','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.13','GPS Find Me','16','commercial','estimation','Pending','TUH_759_R44','2018-07-27','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.2','Trullium','8','commercial','estimation','Pending','PRV_637_R28','2018-08-01','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.3','Bootstrap','3.4','open source','estimation','Submitted','UIW_997_R22','2018-08-01','Inspection Step','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.4','jQuery','3.1.1','open source','estimation','Approved','DHK_965_R1','2018-08-03','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.5','(a) Color Picker','1.8','internal','estimation','Pending','IRN_238_R19','2018-08-04','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.6','Contact Import','14','commercial','estimation','Pending','QBU_687_R12','2018-07-21','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.7','Ajax','16','open source','estimation','Pending','PAK_187_R20','2018-07-22','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.8','Google Maps','v2.3','API','estimation','Approved','INE_557_R31','2018-07-23','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-77','(a) Address Book','77','77.77.9','mySQL','10','open source','estimation','Pending','JKU_647_R16','2018-07-23','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.1','Apache','13','open source','estimation','Submitted','FJK_984_R33','2019-04-14','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.10','(a) Picture Place','8.17','internal','on hold','Approved','ONK_829_R42','2019-04-19','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.11','White Pages','2019','commercial','on hold','Approved','RTB_148_R17','2019-04-19','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.12','Acrobat Reader','9','commercial','on hold','Approved','MUE_712_R18','2019-04-20','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.13','GPS Find Me','17','commercial','on hold','Pending','STI_940_R48','2019-04-20','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.2','Trullium','9','commercial','on hold','Submitted','HFL_553_R5','2019-04-22','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.3','Bootstrap','4','open source','on hold','Submitted','SBB_168_R35','2019-04-22','Inspection Step','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.4','jQuery','3.2','open source','on hold','Pending','WSM_941_R45','2019-04-22','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.5','(a) Color Picker','1.9','internal','on hold','Pending','PIH_107_R49','2019-04-24','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.6','Contact Import','14.1','commercial','on hold','Pending','JTZ_227_R31','2019-04-14','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.7','Ajax','17','open source','on hold','Approved','KWZ_284_R6','2019-04-14','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.8','Google Maps','v3.0','API','on hold','Pending','TNG_125_R12','2019-04-15','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-78','(a) Address Book','78','78.78.9','mySQL','11','open source','on hold','Pending','SZO_533_R12','2019-04-18','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.1','Apache','14','open source','on hold','Pending','JUJ_214_R18','2019-04-25','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.10','(a) Picture Place','8.18','internal','estimation','Pending','YZE_828_R17','2019-05-07','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.11','White Pages','2019','commercial','estimation','Submitted','CCI_730_R49','2019-05-08','Inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.12','Acrobat Reader','9','commercial','estimation','Pending','DGT_930_R36','2019-05-08','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.13','GPS Find Me','18','commercial','estimation','Pending','USP_305_R31','2019-05-08','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.2','Trullium','9','commercial','estimation','Approved','JNQ_522_R1','2019-05-09','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.3','Bootstrap','4','open source','estimation','Pending','TUS_858_R33','2019-05-10','Inspection Step','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.4','jQuery','3.2','open source','estimation','Pending','AEE_883_R10','2019-05-12','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.5','(a) Color Picker','1.9','internal','estimation','Pending','CQG_479_R37','2019-05-12','inspection Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.6','Contact Import','14.2','commercial','estimation','Pending','LFQ_555_R7','2019-04-25','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.7','Ajax','18','open source','estimation','Approved','CNK_138_R24','2019-04-28','Approval Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.8','Google Maps','v3.1','API','estimation','Pending','HZS_660_R38','2019-04-28','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-79','(a) Address Book','79','79.79.9','mySQL','12','open source','estimation','Pending','QDW_847_R25','2019-05-05','Review Step','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.1','RedHat','3','open source','released','released','ESP_627_R48','2016-05-04','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.10','jQuery','3','open source','released','released','HMS_689_R26','2016-05-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.2','RSS Feed Reader','2','commercial','released','released','BMH_269_R21','2016-05-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.3','Acrobat Reader','6','commercial','released','released','DHD_508_R39','2016-05-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.4','(a) Color Picker','1.1','internal','released','released','TPJ_682_R29','2016-05-05','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.5','(a) FileView','2.01','internal','released','released','MIJ_114_R39','2016-05-07','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.6','Bootstrap','2','open source','released','released','SXV_761_R38','2016-05-07','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.7','Datatable','2','open source','released','released','AXN_802_R28','2016-05-07','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.8','Ajax','9','open source','released','released','GWV_688_R44','2016-05-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-5','(a) Book Saver','3','5.3.9','Library Link','v10','commercial','released','released','WFC_274_R29','2016-05-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.1','RedHat','4','open source','released','released','HSV_582_R45','2016-05-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.10','jQuery','3','open source','released','released','YZV_755_R11','2016-05-23','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.2','RSS Feed Reader','3','commercial','released','released','BIB_849_R48','2016-05-25','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.3','Acrobat Reader','6','commercial','released','released','AGL_830_R41','2016-05-27','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.4','(a) Color Picker','1.2','internal','released','released','YPR_177_R7','2016-05-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.5','(a) FileView','2.02','internal','released','released','AID_218_R33','2016-05-14','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.6','Bootstrap','2','open source','released','released','YQK_612_R9','2016-05-16','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.7','Datatable','2','open source','released','released','ICC_241_R11','2016-05-16','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.8','Ajax','10','open source','released','released','UJC_854_R46','2016-05-17','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-51','(a) Book Saver','4','51.4.9','Library Link','v11','commercial','released','released','HHC_983_R40','2016-05-17','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.1','RedHat','5','open source','released','released','XJT_995_R16','2016-12-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.10','Library Link','v12','commercial','released','released','FWX_928_R40','2016-12-10','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.2','jQuery','3','open source','released','released','ABE_640_R3','2016-12-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.3','RSS Feed Reader','4','commercial','released','released','ZCG_851_R34','2016-12-02','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.4','Acrobat Reader','6','commercial','released','released','HJS_824_R36','2016-12-03','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.5','(a) Color Picker','1.3','internal','released','released','KKY_194_R44','2016-12-03','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.6','(a) FileView','2.03','internal','released','released','ZJW_319_R25','2016-12-03','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.7','Bootstrap','2','open source','released','released','IWM_220_R15','2016-12-05','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.8','Datatable','2.1','open source','released','released','YVU_797_R43','2016-12-06','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-52','(a) Book Saver','5','52.5.9','Ajax','11','open source','released','released','ZPS_112_R15','2016-12-09','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.1','RedHat','6','open source','released','released','LJP_952_R33','2016-12-11','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.10','Library Link','v13','commercial','released','released','SSW_537_R22','2016-12-22','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.2','jQuery','3','open source','released','released','TEW_686_R41','2016-12-22','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.3','RSS Feed Reader','5','commercial','released','released','ZXQ_912_R40','2016-12-12','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.4','Acrobat Reader','7','commercial','released','released','BVB_121_R35','2016-12-13','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.5','(a) Color Picker','1.4','internal','released','released','MMJ_986_R40','2016-12-13','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.6','(a) FileView','2.04','internal','released','released','BLO_188_R31','2016-12-14','completed','');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.7','Bootstrap','3','open source','released','released','WUA_439_R40','2016-12-18','completed','open source, no commercial support');
INSERT INTO `sbom` (`app_id`,`app_name`,`app_version`,`cmp_id`,`cmp_name`,`cmp_version`,`cmp_type`,`app_status`,`cmp_status`,`request_id`,`request_date`,`request_step`,`notes`) VALUES ('ALI-53','(a) Book Saver','6','53.6.8','Datatable','2.1','open source','released','released','ZDR_187_R29','2016-12-18','completed','');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `sbom`
--
ALTER TABLE `sbom`
  ADD PRIMARY KEY (`row_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `sbom`
--
ALTER TABLE `sbom`
  MODIFY `row_id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
